version: "3.9"
services:
  api:
    build: .
    restart: on-failure
    depends_on:
      - db
    environment:
      - DEBUG=true
      - SPRING_R2DBC_URL=r2dbc:mysql://db/testdb
      - MANAGEMENT_ENDPOINTS_ENABLEDBYDEFAULT=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=info,health,flyway,prometheus
      - MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS=always
      - MANAGEMENT_ENDPOINT_HEALTH_SHOWCOMPONENTS=always
    ports:
      - 8080:8080
  db:
    image: mysql:8.0.22
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/